name: Build and Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - master
jobs:
  hawkscan:
    name: Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Docker Build
        run: docker-compose build
      - name: Run GraphAPI
        run: docker-compose up -d
      - name: Run HawkScan
        env:
          API_KEY: ${{secrets.HAWK_API_KEY}}
        run: >
          docker run -v $(pwd):/hawk -t --network vuln-graphql_default
          -e API_KEY="${API_KEY}"
          stackhawk/hawkscan stackhawk.yml stackhawk-github.yml
